-- 소속(dept, 넓은 단위)/부서(team, 세부 파트)를 분리해서 정확히 채우는 스크립트
-- 이름 + 현재 dept 값으로 정확히 매칭해서 업데이트합니다 (동명이인 안전)

update employees set dept='영업그룹', team='해외영업팀' where name='김태봉' and dept='해외영업팀';
update employees set dept='원텍연구원 판교연구소', team='CA(Clinical Application)파트' where name='홍선옥' and dept='CA(Clinical Application)파트';
update employees set dept='글로벌영업팀', team='써지컬 사업파트' where name='이재성' and dept='써지컬 사업파트';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='이지영' and dept='레이저광학팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='이동현' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='엔지니어링팀' where name='조성철' and dept='엔지니어링팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='윤현식' and dept='인허가팀';
update employees set dept='원텍연구원 판교연구소', team='CA(Clinical Application)파트' where name='이지유' and dept='CA(Clinical Application)파트';
update employees set dept='원텍연구원 판교연구소', team='CRO파트' where name='임해진' and dept='CRO파트';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='오동환' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='장인형' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='김효진' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이형기' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀 구매팀' where name='김명일' and dept='품질관리팀 구매팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='이주훤' and dept='글로벌물류관리팀';
update employees set dept='글로벌영업팀', team='영업전략파트' where name='손정환' and dept='영업전략파트';
update employees set dept='한국영업팀', team='영업 1파트' where name='조만식' and dept='영업 1파트';
update employees set dept='한국영업팀', team='영업 2파트' where name='송재원' and dept='영업 2파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='최성우' and dept='해외CS파트';
update employees set dept='경영기획팀', team='인사파트(대)' where name='복민규' and dept='인사파트(대)';
update employees set dept='경영기획팀', team='감사법무파트' where name='김주홍' and dept='감사법무파트';
update employees set dept='글로벌영업팀', team='써지컬 사업파트' where name='김진우' and dept='써지컬 사업파트';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='오석원' and dept='레이저광학팀';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='문준영' and dept='레이저광학팀';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='박성민' and dept='레이저광학팀';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='추경덕' and dept='레이저광학팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='송호정' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='백영준' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='문장현' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='이정훈' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='김덕수' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='박승훈' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='이창우' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='윤종진' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='이채린' and dept='전기전자팀';
update employees set dept='원텍연구원 연구소', team='엔지니어링팀' where name='전달영' and dept='엔지니어링팀';
update employees set dept='원텍연구원 연구소', team='엔지니어링팀' where name='김승도' and dept='엔지니어링팀';
update employees set dept='원텍연구원 연구소', team='엔지니어링팀' where name='문종인' and dept='엔지니어링팀';
update employees set dept='원텍연구원 연구소', team='엔지니어링팀' where name='최인광' and dept='엔지니어링팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='송성순' and dept='인허가팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='김성민' and dept='인허가팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='박병훈' and dept='인허가팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='박소현' and dept='인허가팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='김서로' and dept='인허가팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='전채리' and dept='인허가팀';
update employees set dept='원텍연구원 연구소', team='연구지원팀' where name='유성미' and dept='연구지원팀';
update employees set dept='원텍연구원 판교연구소', team='연구 1파트' where name='유승민' and dept='연구 1파트';
update employees set dept='원텍연구원 판교연구소', team='연구 1파트' where name='김유민' and dept='연구 1파트';
update employees set dept='원텍연구원 판교연구소', team='연구 1파트' where name='이시윤' and dept='연구 1파트';
update employees set dept='원텍연구원 판교연구소', team='연구 2파트' where name='김주형' and dept='연구 2파트';
update employees set dept='원텍연구원 판교연구소', team='CA(Clinical Application)파트' where name='이혜빈' and dept='CA(Clinical Application)파트';
update employees set dept='글로벌영업팀', team='써지컬 사업파트' where name='이도희' and dept='써지컬 사업파트';
update employees set dept='원텍연구원 판교연구소', team='CA(Clinical Application)파트' where name='김도희' and dept='CA(Clinical Application)파트';
update employees set dept='글로벌영업팀', team='영업전략파트' where name='황수원' and dept='영업전략파트';
update employees set dept='글로벌영업팀', team='영업전략파트' where name='이혜린' and dept='영업전략파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='이일선' and dept='지역영업파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='이창윤' and dept='지역영업파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='김한결' and dept='지역영업파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='이혜은' and dept='지역영업파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='왕혜진' and dept='지역영업파트';
update employees set dept='글로벌영업팀', team='해외법인영업파트' where name='성시헌' and dept='해외법인영업파트';
update employees set dept='글로벌영업팀', team='해외법인영업파트' where name='장이삭' and dept='해외법인영업파트';
update employees set dept='글로벌영업팀', team='해외법인영업파트' where name='박민수' and dept='해외법인영업파트';
update employees set dept='한국영업팀', team='영업 1파트' where name='강지형' and dept='영업 1파트';
update employees set dept='한국영업팀', team='영업 2파트' where name='김량현' and dept='영업 2파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='김광영' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='오현석' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='이준희' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='유선원' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='구세환' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='박종훈' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='김병진' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='하동균' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='민병인' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='원희철' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='서명섭' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='전성준' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='정병준' and dept='국내CS파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='윤용진' and dept='국내CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='박종덕' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='김한기' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='모삽' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='김형기' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='김창훈' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='성주홍' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='성주영' and dept='해외CS파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='프레데리코' and dept='해외CS파트';
update employees set dept='전략마케팅팀', team='상품전략파트' where name='박한별' and dept='상품전략파트';
update employees set dept='전략마케팅팀', team='브랜드전략파트' where name='노시현' and dept='브랜드전략파트';
update employees set dept='B2C사업부', team='B2C사업팀' where name='전정태' and dept='B2C사업팀';
update employees set dept='B2C사업부', team='B2C사업팀' where name='이욱연' and dept='B2C사업팀';
update employees set dept='B2C사업부', team='B2C사업팀' where name='최순오' and dept='B2C사업팀';
update employees set dept='B2C사업부', team='B2C사업팀' where name='용경연' and dept='B2C사업팀';
update employees set dept='B2C사업부', team='B2C사업팀' where name='김소라' and dept='B2C사업팀';
update employees set dept='경영기획팀', team='인사파트(판)' where name='최기환' and dept='인사파트(판)';
update employees set dept='경영기획팀', team='인사파트(대)' where name='강희천' and dept='인사파트(대)';
update employees set dept='경영기획팀', team='재무파트(대)' where name='배준철' and dept='재무파트(대)';
update employees set dept='경영기획팀', team='재무파트(대)' where name='한우리' and dept='재무파트(대)';
update employees set dept='경영기획팀', team='재무파트(대)' where name='김용순' and dept='재무파트(대)';
update employees set dept='경영기획팀', team='재무파트(판)' where name='김호성' and dept='재무파트(판)';
update employees set dept='경영기획팀', team='재무파트(대)' where name='이명준' and dept='재무파트(대)';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='고지훈' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='김우람' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='천영한' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='김준수' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='황인록' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='조윤형' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='이정은' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='고선호' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='조경래' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='윤현경' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='박성훈' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='서진욱' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='이상열' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='박진택' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='김진성' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='전이섭' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='유현식' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='김홍인' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='김용구' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='최영락' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='연경모' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='이종영' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='민정훈' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='이세용' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='주하늘' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='지민호' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='이정훈' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='한경흠' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='이혁주' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='김재민' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='송두웅' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='김민호' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='황성문' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='박창욱' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='김성열' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='최영원' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='유재혁' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='이창현' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='강민성' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='김이환' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='김송' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='양선호' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='정규희' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='정현우' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='박영수' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='이준영' and dept='생산기술 3팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이진화' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='박정현' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='장영섭' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='김은정' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='염예선' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='정용예' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='태안진' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='강주희' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이선희' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이지연' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='홍이슬' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이수연' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='전순희' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='차미자' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='김경란' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='홍진영' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='김영정' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='박은정' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이윤희' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='이호은' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='홍기석' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='염현선' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='이영선' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='유현준' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='천영민' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='김진성' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='강석인' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='장윤정' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='이한샘' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='이종덕' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='김현익' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='조효진' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='김진영' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='최기준' and dept='구매팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='최민국' and dept='구매팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='장완주' and dept='구매팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='김승겸' and dept='구매팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='박건호' and dept='구매팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='최수규' and dept='구매팀';
update employees set dept='원텍연구원 판교연구소', team='S/W 개발 파트' where name='곽미라' and dept='S/W 개발 파트';
update employees set dept='원텍연구원 판교연구소', team='S/W 개발 파트' where name='김규홍' and dept='S/W 개발 파트';
update employees set dept='해외법인', team='동남아총괄' where name='김기중' and dept='동남아총괄';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='김대연' and dept='전기전자팀';
update employees set dept='원텍연구원 판교연구소', team='S/W 개발 파트' where name='김동석' and dept='S/W 개발 파트';
update employees set dept='글로벌영업팀', team='해외법인영업파트' where name='김선준' and dept='해외법인영업파트';
update employees set dept='원텍연구원 판교연구소', team='CRO파트' where name='김설화' and dept='CRO파트';
update employees set dept='고객만족팀', team='해외CS파트' where name='김인호' and dept='해외CS파트';
update employees set dept='원텍연구원 판교연구소', team='CA(Clinical Application)파트' where name='김정윤' and dept='CA(Clinical Application)파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='김종완' and dept='지역영업파트';
update employees set dept='원텍연구원 판교연구소', team='H/W 개발 파트' where name='김종훈' and dept='H/W 개발 파트';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='김지환' and dept='구매팀';
update employees set dept='해외법인', team='미국법인' where name='김진수' and dept='미국법인';
update employees set dept='원텍연구원 판교연구소', team='CRO파트' where name='남연석' and dept='CRO파트';
update employees set dept='전략마케팅팀', team='브랜드전략파트' where name='노승환' and dept='브랜드전략파트';
update employees set dept='글로벌영업팀', team='영업전략파트' where name='박민우' and dept='영업전략파트';
update employees set dept='경영기획팀', team='감사법무파트' where name='박병건' and dept='감사법무파트';
update employees set dept='경영기획팀', team='인사파트' where name='박서현' and dept='인사파트';
update employees set dept='경영기획팀', team='재무파트(대)' where name='박진숙' and dept='재무파트(대)';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='백승봉' and dept='품질관리팀';
update employees set dept='글로벌영업팀', team='해외법인영업파트' where name='서연경' and dept='해외법인영업파트';
update employees set dept='고객만족팀', team='국내CS파트' where name='송상민' and dept='국내CS파트';
update employees set dept='미래전략실', team='전략파트' where name='송세운' and dept='전략파트';
update employees set dept='원텍연구원 판교연구소', team='H/W 개발 파트' where name='양재원' and dept='H/W 개발 파트';
update employees set dept='원텍연구원 판교연구소', team='S/W 개발 파트' where name='유재원' and dept='S/W 개발 파트';
update employees set dept='원텍연구원 판교연구소', team='CRO파트' where name='윤태경' and dept='CRO파트';
update employees set dept='미래전략실', team='전략파트' where name='이규민' and dept='전략파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='이미령' and dept='지역영업파트';
update employees set dept='전략마케팅팀', team='상품전략파트' where name='이서현' and dept='상품전략파트';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='이석환' and dept='생산기술 3팀';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='이성혁' and dept='인허가팀';
update employees set dept='미래전략실', team='전략파트' where name='이연우' and dept='전략파트';
update employees set dept='원텍연구원 생산기술연구소', team='글로벌물류관리팀' where name='이윤아' and dept='글로벌물류관리팀';
update employees set dept='원텍연구원 판교연구소', team='H/W 개발 파트' where name='이재홍' and dept='H/W 개발 파트';
update employees set dept='원텍연구원 연구소', team='전기전자팀' where name='이준규' and dept='전기전자팀';
update employees set dept='고객만족팀', team='해외CS파트' where name='이형섭' and dept='해외CS파트';
update employees set dept='전략마케팅팀', team='브랜드전략파트' where name='임단꿈' and dept='브랜드전략파트';
update employees set dept='미래전략실', team='써지컬파트' where name='임석호' and dept='써지컬파트';
update employees set dept='전략마케팅팀', team='브랜드전략파트' where name='장세희' and dept='브랜드전략파트';
update employees set dept='전략마케팅팀', team='브랜드전략파트' where name='장연재' and dept='브랜드전략파트';
update employees set dept='원텍연구원 판교연구소', team='H/W 개발 파트' where name='장현호' and dept='H/W 개발 파트';
update employees set dept='글로벌영업팀', team='지역영업파트' where name='정성욱' and dept='지역영업파트';
update employees set dept='원텍연구원 연구소', team='엔지니어링팀' where name='정성원' and dept='엔지니어링팀';
update employees set dept='경영기획팀', team='인사파트' where name='정영태' and dept='인사파트';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 3팀' where name='조성연' and dept='생산기술 3팀';
update employees set dept='한국영업팀', team='영업 2파트' where name='최준수' and dept='영업 2파트';
update employees set dept='원텍연구원 연구소', team='인허가팀' where name='최지민' and dept='인허가팀';
update employees set dept='경영기획팀', team='감사법무파트' where name='허용석' and dept='감사법무파트';
update employees set dept='경영기획팀', team='재무파트(대)' where name='홍성현' and dept='재무파트(대)';
update employees set dept='전략마케팅팀', team='브랜드전략파트' where name='홍예인' and dept='브랜드전략파트';
update employees set dept='원텍연구원 연구소', team='연구지원팀' where name='황소영' and dept='연구지원팀';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='황시온' and dept='레이저광학팀';
update employees set dept='한국영업팀', team='영업 1파트' where name='양준욱' and dept='영업 1파트';
update employees set dept='한국영업팀', team='영업 1파트' where name='김세현' and dept='영업 1파트';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='강석주' and dept='생산기술 1팀';
update employees set dept='고객만족팀', team='국내CS파트' where name='송인선' and dept='국내CS파트';
update employees set dept='경영기획팀', team='인사파트(판)' where name='김해미' and dept='인사파트(판)';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='한동빈' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='임혜란' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 1팀' where name='이희명' and dept='생산기술 1팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='이채현' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='오순주' and dept='TCF팀';
update employees set dept='글로벌영업팀', team='해외법인영업파트' where name='김병호' and dept='해외법인영업파트';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='박수진' and dept='TCF팀';
update employees set dept='원텍연구원 연구소', team='인허가팀(판교)' where name='홍성문' and dept='인허가팀(판교)';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='김은주' and dept='구매팀';
update employees set dept='미래전략실', team='전략기획팀-상품전략파트' where name='이재훈' and dept='전략기획팀-상품전략파트';
update employees set dept='미래전략실', team='전략기획팀-상품전략파트' where name='원윤조' and dept='전략기획팀-상품전략파트';
update employees set dept='미래전략실', team='전략기획팀-대외협력파트' where name='김범준' and dept='전략기획팀-대외협력파트';
update employees set dept='글로벌영업실', team='메디컬솔루션팀' where name='황보영' and dept='메디컬솔루션팀';
update employees set dept='글로벌영업실', team='한국영업1파트' where name='김정국' and dept='한국영업1파트';
update employees set dept='글로벌영업실', team='해외영업팀-미주/아시아파트' where name='정승호' and dept='해외영업팀-미주/아시아파트';
update employees set dept='글로벌영업실', team='써지컬사업파트(메디컬솔루션팀)' where name='김해나' and dept='써지컬사업파트(메디컬솔루션팀)';
update employees set dept='글로벌영업실', team='해외영업팀-미주/아시아파트' where name='윤재경' and dept='해외영업팀-미주/아시아파트';
update employees set dept='글로벌영업실', team='한국영업1파트' where name='구주영' and dept='한국영업1파트';
update employees set dept='글로벌영업실', team='한국영업1파트' where name='신수빈' and dept='한국영업1파트';
update employees set dept='글로벌영업실', team='한국영업2파트' where name='김영훈' and dept='한국영업2파트';
update employees set dept='글로벌영업실', team='해외영업팀-해외법인영업파트' where name='김지홍' and dept='해외영업팀-해외법인영업파트';
update employees set dept='마케팅실', team='브랜드전략파트' where name='김청솔' and dept='브랜드전략파트';
update employees set dept='마케팅실', team='CA파트' where name='임남주' and dept='CA파트';
update employees set dept='마케팅실', team='브랜드전략파트' where name='정원경' and dept='브랜드전략파트';
update employees set dept='마케팅실', team='CA파트' where name='안희진' and dept='CA파트';
update employees set dept='마케팅실', team='CA파트' where name='권은채' and dept='CA파트';
update employees set dept='원텍연구원 연구소', team='레이저광학팀' where name='김지수' and dept='레이저광학팀';
update employees set dept='판교연구소', team='H/W 개발 파트' where name='윤섭' and dept='H/W 개발 파트';
update employees set dept='판교연구소', team='H/W 개발 파트' where name='이도현' and dept='H/W 개발 파트';
update employees set dept='판교연구소', team='H/W 개발 파트' where name='강병은' and dept='H/W 개발 파트';
update employees set dept='판교연구소', team='S/W 개발 파트' where name='김하나' and dept='S/W 개발 파트';
update employees set dept='판교연구소', team='인허가팀' where name='차지영' and dept='인허가팀';
update employees set dept='판교연구소', team='판교 인허가파트' where name='김민경' and dept='판교 인허가파트';
update employees set dept='판교연구소', team='판교 인허가파트' where name='김솔이' and dept='판교 인허가파트';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='박윤근' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='생산기술 2팀' where name='최태훈' and dept='생산기술 2팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='안현정' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='TCF팀' where name='노은혜' and dept='TCF팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='고호진' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='품질관리팀' where name='안중선' and dept='품질관리팀';
update employees set dept='원텍연구원 생산기술연구소', team='구매팀' where name='엄지후' and dept='구매팀';
update employees set dept='경영기획팀', team='판교 인사파트' where name='김태형' and dept='판교 인사파트';
update employees set dept='경영기획팀', team='판교 인사파트' where name='정예림' and dept='판교 인사파트';
update employees set dept='경영기획팀', team='정보보호파트' where name='김성필' and dept='정보보호파트';
update employees set dept='경영기획팀', team='정보보호파트' where name='유재준' and dept='정보보호파트';
